### ISSUE TITLE
CSS - styling page 1 

### ISSUE THREAD

**Issue by Roqieux** [sjones-njones/Group-Project-1#11]
Reference the excalidraw 

https://excalidraw.com/#room=6e73621f9df80224d853,GTAgwmTqq_OMcL2iE4bHIA

**Comment by lcurtis0** [comment]
Currently working on this one

**Comment by Roqieux** [comment]
Page 1 has a good start, think we can make this a little more polished. Some issues may have occurred during merge into main branch as there were conflicts. 

Currently, when re-sizing the page I get behavior like: 
<img width="616" alt="image" src="https://github.com/sjones-njones/Group-Project-1/assets/133982261/f7dcdea3-e3ee-4bc4-885b-250080545d5c">

also, sorry if I broke the buttons when doing the merge :/

**Comment by Roqieux** [comment]
would it also be possible to get both input options to fit within the view port without the need to scroll? 

This could be done with columns to make the address input a bit more wide so it takes up less vertical space. I have a mockup here which I had worked on prior to seeing the changes you had pushed 

<img width="579" alt="image" src="https://github.com/sjones-njones/Group-Project-1/assets/133982261/879b9ab1-3017-4c33-aa3e-f7d60aa71162">

<img width="320" alt="image" src="https://github.com/sjones-njones/Group-Project-1/assets/133982261/c79e32da-d479-4236-ad54-d8fcda61b3dc">

code I had for managing columns: 

`  <main>
    <section id="address-search-container"
      class="user-input-container container has-background-primary-light is-align-content-center p-4 m-4 ">
      <div>
        <h2 class="has-text-weight-medium  is-size-4-tablet">Input an address below</h2>
      </div>
      <form id="address-input-form">
        

        <div class="mt-3 columns is-gapless is-centered">
          <div class="column is-one-quarter">
            
            <label class="label" for="street-address">Street Address</label>
            <input name="street-address" id="street-address" type="text" class="form-input-large" />

            
            <label class="label" for="city-address">City</label>
            <input name="city-address" id="city-address" type="text" class="form-input-med" />

            
            <label class="label" for="zip-address">Zip Code</label>
            <input name="zip-address" id="zip-address" type="text" class="form-input-short" />
          </div>

          <div class="column is-one-quarter">
            
            <label class="label" for="Apt">Apt</label>
            <input name="apt-number" id="apt-number" type="text" class="form-input-short" />

            
            <label class="label" for="state-select">State</label>
            <select class="input-select" id="state-select"></select>
          </div>
        </div>

        
        <button type="submit" id="btnSubmit" class="button is-primary is-rounded"> Submit
        </button>

      </form>
    </section>`
