### ISSUE TITLE
Javascript - fetch requests 

### ISSUE THREAD

**Issue by Roqieux** [sjones-njones/Group-Project-1#6]
write fetch requests to both 

coinapi.io 
curl https://rest.coinapi.io/v1/exchangerate/BTC/USD 
  --request GET
  --header "X-CoinAPI-Key: 73034021-THIS-IS-SAMPLE-KEY"

rapidapi.com -zillow
https://docs.coinapi.io/market-data/rest-api/exchange-rates

We need - Bitcoin current price in USD to be saved and potentially stored as a local variable 
We need - zillow pull to search via ExtendedSearch for property address - should return a single zpid 
We need - zillow pull using zpid to query property value - zestimate 

we need - zillow pull to pull properties in a given city / state / city&state and store the list in local storage. list should be stored as an array and delete any existing array stored as the property query

**Comment by lcurtis0** [comment]
I can take this one
